# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint PR Annotations with Reviewdog

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['*']
  workflow_run:
    workflows: ['Draft Release on Tag']
    types:
      - completed

jobs:
  eslint-reviewdog:
    name: Run ESLint Scanning with Reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install ESLint Formatter for SARIF
        run: |
          yarn add @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint with TypeScript Config + Reviewdog
        uses: reviewdog/action-eslint@v1.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: >-
            --config eslint.config.ts
            --ext .js,.ts,.tsx,.vue
            .
          fail_level: error
          level: warning
        env:
          NODE_OPTIONS: '--require jiti/register' # Necessary for TypeScript config
