# Automatically update version in package.json and generate package for
# Windows, Linux, and macOS, and upload to draft release on GitHub
# when tagging a new release.

name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*' # Only match semantic versioning tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag and branch
        id: info
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BRANCH=$(git branch -r --contains "$TAG_NAME" | grep -v '\->' | grep -v 'origin/HEAD' | sed 's|origin/||' | head -n 1)
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Exit if branch is main (protected)
        if: steps.info.outputs.branch == 'main'
        run: |
          echo "Cannot automatically update version and package release on protected branch 'main'."
          exit 1

      - name: Checkout specific branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.info.outputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Update package.json version if different
        id: version_check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          echo "Tag version: ${{ steps.info.outputs.tag }}"

          if [ "$CURRENT_VERSION" = "${{ steps.info.outputs.tag }}" ]; then
            echo "Version matches tag. Skipping version bump."
            echo "skip_bump=true" >> $GITHUB_OUTPUT
          else
            yarn version --new-version ${{ steps.info.outputs.tag }} --no-git-tag-version
            git commit -am "chore: update version to ${{ steps.info.outputs.tag }}"
            git push origin ${{ steps.info.outputs.branch }}
            echo "skip_bump=false" >> $GITHUB_OUTPUT
          fi

      - name: Move tag to latest commit if version bumped
        if: steps.version_check.outputs.skip_bump == 'false'
        run: |
          git tag -d ${{ steps.info.outputs.tag }}
          git push origin :refs/tags/${{ steps.info.outputs.tag }}
          git tag ${{ steps.info.outputs.tag }}
          git push origin ${{ steps.info.outputs.tag }}
